FROM node:22-alpine

WORKDIR /app

# Устанавливаем необходимые зависимости для компиляции нативных модулей
RUN apk add --no-cache python3 make g++ \
  && corepack enable

COPY package.json pnpm-lock.yaml* ./

# Устанавливаем зависимости
RUN pnpm install --frozen-lockfile=false

# Убираем COPY . . так как все файлы монтируются через volumes

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]
